# Generated by Django 4.2.4 on 2023-10-07 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='ORDERDATE',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 7), null=True),
        ),
    ]
