# Generated by Django 4.1.7 on 2023-09-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEQ_NUM', models.IntegerField(default=0)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
                ('AMOUNT', models.IntegerField(blank=True, null=True)),
                ('PRODUCT_ID', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('SALES_ORDER_ID', models.ForeignKey(db_column='SALES_ORDER_ID', on_delete=django.db.models.deletion.CASCADE, to='sales_orders.salesorder')),
            ],
        ),
    ]
