# Generated by Django 4.1.7 on 2023-09-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_orders', '0001_initial'),
        ('products', '0004_alter_product_cost_alter_product_quantity_on_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('SALES_ORDER_ID', models.ForeignKey(db_column='SALES_ORDER_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sales_orders.salesorder')),
                ('SEQ_NUM', models.IntegerField(default=0)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
                ('AMOUNT', models.IntegerField(blank=True, null=True)),
                ('PRODUCT_ID', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
