# Generated by Django 4.1.7 on 2023-09-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
        ('sales_order_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderproduct',
            name='SALES_ORDER_ID',
            field=models.ForeignKey(db_column='SALES_ORDER_ID', on_delete=django.db.models.deletion.CASCADE, to='sales_orders.salesorder'),
        ),
    ]
