# Generated by Django 4.2.4 on 2023-09-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ledger_entries', '0002_alter_customerledgerentry_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='PAID_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
