# Generated by Django 4.1.7 on 2023-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CUSTOMER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=35, unique=True)),
                ('BALANCE_DUE', models.IntegerField(default=0)),
                ('ADDRESS', models.CharField(max_length=35, null=True)),
                ('STATUS', models.CharField(max_length=35, null=True)),
                ('CONTACT', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
