# Generated by Django 4.1.7 on 2023-10-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales_invoices', '0002_rename_salesinvoice_id_salesinvoice_sales_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='CUSTOMER_ID',
            field=models.ForeignKey(blank=True, db_column='CUSTOMER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
