# Generated by Django 4.2.4 on 2023-10-07 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_invoices', '0003_alter_salesinvoice_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='INVOICE_DATE',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 7), null=True),
        ),
    ]
