# Generated by Django 4.1.7 on 2023-09-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PRODUCT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PRODUCT_NAME', models.CharField(max_length=35, unique=True)),
                ('UOM', models.CharField(blank=True, max_length=35, null=True)),
                ('COST', models.IntegerField(blank=True, default=0, null=True)),
                ('QUANTITY_ON_HAND', models.IntegerField(blank=True, default=0, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
