# Generated by Django 4.1.7 on 2023-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRODUCT_NAME',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='STATUS',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
