# Generated by Django 4.1.7 on 2023-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_name_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='COST',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='QUANTITY_ON_HAND',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='STATUS',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='UOM',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
